Cleanup
tesserae/tesserae-v5 pull request #84
Opened 2020-10-29 06:48 UTC by lhambrid

I modified get_inverse_text_frequencies so that it computes inverse frequencies per the paper for sound features as well.  I don't think it made the function significantly longer or more complex, so I chose not to split it.  The only function I chose to split is _score, which is now split into _score and _score_sound.  _get_sound_distance_by_frequency is now obsolete, but I left it in there just in case.

2020-10-29 17:46 UTC, nOkuda requested changes
I've left some comments for consideration.

At a bare minimum, this pull request needs all merge conflicts resolved before it can be merged (let me know if you'd like help with this).

It is also important to document the significantly different way in which t_positions and s_positions are defined in _score_sound as compared to _score.

2020-10-29 17:46 UTC, nOkuda commented on tesserae/utils/calculations.py
> +        return inv_frequencies
Since the denominator used in the sound case of this function is different from the denominator used for other cases of this function, it seems better to separate the sound case into a different function. That new function could then be useful if in the future, someone decides to score lemma search in the same way as this new way of sound scoring.

2020-10-29 17:46 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +#                    source_inv_frequencies_getter, s_positions, source_sounds)
Since _score_sound uses t_positions and s_positions different from score, shouldn't it use _get_sound_distance_by_least_frequency instead of _get_distance_by_least_frequency?

2020-10-29 17:46 UTC, nOkuda commented on tesserae/features/trigrams.py
> +        grams = list(grams_set)
In light of the fact that repeated trigrams within a token are disregarded, does the new use of t_positions and s_positions in _score_sound make sense?

2020-11-01 03:31 UTC, lhambrid commented on tesserae/matchers/sparse_encoding.py
> +#                    source_inv_frequencies_getter, s_positions, source_sounds)
No.  t_positions and s_positions generated by _score _sound are lists of the positions of character trigrams in a line, while t_positions and s_positions generated by _score are lists of the positions of words in a line.  Still meets the arguments of _get_distance_by_least_frequency.

2020-11-01 04:17 UTC, lhambrid commented on tesserae/features/trigrams.py
> +        grams = list(grams_set)
Huh, I see how that is a problem.  I made this change so long ago that I no longer remember why I made it.  I did it when we were still scoring based on frequency and distance of words, so I suppose I was trying to reduce redundancy for the sake of efficiency in scoring.  I will remove this change.

2020-11-02 14:59 UTC, nOkuda requested changes
This is looking good.

Please try running `python3 -m pytest -k "mini"` to see if the code crashes. There's one place I think in particular may crash.

The only other change I would really like before merging is taking out the score matrix print statement. It would be annoying to read those print outs in the server logs.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +        inverse frequency as output
Good catch.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +    return min(distances)
Since this function is never used, I would recommend removing it from the code.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +    print('score matrix', scores)
Please take out this print statement.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +#                    source_inv_frequencies_getter, s_positions, source_sounds)
Ah, I see this now.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/matchers/sparse_encoding.py
> +                target_sounds.append(b)
For future reference, it seems strange to append items from one list to another. Especially since target_sounds (and source_sounds) won't be changed, it seems more natural to just assign target_sounds (and source_sounds) directly to the lists the items are being pulled from.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/utils/calculations.py
> +            units.append(cur_tindex)
I have a sneaking suspicion that the code will crash at this line.

2020-11-02 14:59 UTC, nOkuda commented on tesserae/utils/calculations.py
> +    """
This looks great.

2020-11-04 13:33 UTC, lhambrid commented on tesserae/utils/calculations.py
> +            units.append(cur_tindex)
good call.

2020-11-04 13:41 UTC, lhambrid commented on tesserae/matchers/sparse_encoding.py
> +                target_sounds.append(b)
target_unit['features'] = [['tri','rig','igr','gra','ram'] , ['lis','ist','sts'] , ['lis','ist']]
a = ['lis','ist']
b = 'lis'
Trying to avoid making another list of lists.  This unpacks the trigrams to put them all together in just one list.

2020-11-05 13:53 UTC, nOkuda approved these changes
Since the code nominally works, I'll merge this into master. Good job so far.

The most important piece missing is a description of what exactly the new sound search does. Whether you choose to publish that report or not, your report will make future maintenance much easier (imagine not having to reverse engineer v3 sound matching like we had to do). So please write up your work.

The other task left hanging is making sure highlighting works correctly with the sound search results. (I don't know how much you've diverged from the regular search scoring algorithm, but I recall that the original s_positions and t_positions are used for highlighting information. So if you can still grab those, you can look back at what the original _score function did with them.) Please work with Jeff to make sure sound matching works properly on the frontend. I've already let him know to keep a lookout for you.

2020-11-05 13:54 UTC, merged